id: A988D4590
title: A Prayer to the Precious Teacher of Incomparable Kindness, Jamyang Lungtok
  Gyaltsen
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:36:11.315642
  last_modified_at: 2022-02-28 22:36:11.315652
